### ISSUE TITLE
Nothing is built no errors

### ISSUE THREAD

**Issue by mladenp** [lucalanca/grunt-angular-architecture-graph#18]
I installed graphviz on my Windows and added it PATH. Installed grunt-graphviz and grunt-angular-architecture-graph. 
I added:
     "architecture": [
                       "/www/js/app.js"
    ]
and: ` grunt.loadNpmTasks('grunt-angular-architecture-graph'); `
But when i run grunt nothing happens, it doesn't put anything inside architecture folder.

**Comment by lucalanca** [comment]
Can you share your whole grunt-angular-architecture-graph configuration? It should look like:

```
angular_architecture_graph: {
  diagram: {
    files: {
       "architecture": [
         "<%= projectConfig.app %>/<%= projectConfig.project %>/**/*.js"
       ]
    }
  }
}
```

Also, are you running ``grunt angular-architecture-graph` ?

**Comment by mladenp** [comment]
Ah, thanks, i forgot to register it as default task. 
Now it creates folder and files but all.png and modules.png are empty images?

**Comment by lucalanca** [comment]
Are these the only images that appear empty? Do you have any images being created for each module?

If not, are you sure you're pointing to the right file?

**Comment by mladenp** [comment]
Yes, there is generic legend.png file thats ok and there are dot files inside dot folder.
I am pointing it to one file with one module inside. The file is JSHinted without any errors. 
Graphviz is working fine from command line.

**Comment by lucalanca** [comment]
This is definitely weird. Can you write an example of your module so I can try to reproduce this error?

**Comment by mladenp** [comment]
Here it is: http://pastebin.com/KbjJcJEq
I tried some other files but still nothing.

**Comment by lucalanca** [comment]
Downloaded this file and added as tests to this repo. You can see it in `example` branch. The specific configuration is in https://github.com/lucalanca/grunt-angular-architecture-graph/blob/example/grunt/angular_architecture_graph.js#L21

I got no problems and one of the generated diagrams is all.png like follows:

![all](https://cloud.githubusercontent.com/assets/389459/5857809/bd9f9edc-a24e-11e4-91cf-ff7b7884b282.png)

**Comment by mladenp** [comment]
Ah, i was stupid i should have added full path to my angular files.
You may want to mention that in readme, projectConfig.app is a little confusing, mention that full path to .js file is required (like C:/Users/Mladen/Mirage/www/js/app.js)

btw this is awesome stuff :+1:

**Comment by lucalanca** [comment]
Glad I could help.

Usually I can pass the path starting from the root of the project (where Gruntfile.js lies). Is this a windows thing? (I run OSX)

**Comment by mladenp** [comment]
Yup on Windows, i am assuming it needs full path so that graphviz can access it correctly.
